AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app
  Main frontend for blogs or whatever WE decide to publish
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HfmdFrontendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Environment:
        Variables:
          HFMD_API_TOKEN: e4d5575c1a051f0780b9ee554dff4736b44b1af730ad069511d115a5fb901088aa0e407e4c7d92b6a4c46fef7d164ab3aab534d5c10164173beccb457d9acb08fe8a36b2ef0f92d35eb9986daf43f89eaa3f69115bd04f1434aef77b28c2f4846d98dba42e978f3f712e47ff09892a935b5de68dcf42b6ce092c761631437fa9
          HFMD_URL: https://cms.homeformydome.com
      Events:
        SimpleApp:
          Type: Api
          Properties:      
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimpleAppApi:
    Description: "API Gateway endpoint URL for Prod stage for HfmdFrontendFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/HfmdFrontendFunction/"
  HfmdFrontendFunction:
    Description: "HfmdFrontendFunction Lambda Function ARN"
    Value: !GetAtt HfmdFrontendFunction.Arn
  HfmdFrontendFunctionIamRole:
    Description: "Implicit IAM Role created for HfmdFrontendFunction"
    Value: !GetAtt HfmdFrontendFunctionRole.Arn